spring:
  cloud:
    config:
      fail-fast: true
eureka:
  instance:
    prefer-ip-address: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
